dist: out

before:
  hooks:
    - scripts/set-executable.sh

builds:
  - builder: prebuilt
    binary: pixlet

    targets:
      - darwin_amd64
      - darwin_arm64
      - linux_amd64
      - linux_arm64
      - windows_amd64

    prebuilt:
      path: build/{{ .Os }}_{{ .Arch }}/pixlet{{ .Ext }}

checksum:
  name_template: "checksums.txt"

changelog:
  sort: asc

brews:
  - tap:
      owner: tidbyt
      name: homebrew-tidbyt

    commit_author:
      name: tidbyt-bot
      email: bot@tidbyt.com

    homepage: https://github.com/tidbyt/pixlet

    description: App runtime and UX toolkit for pixel-based apps.

    dependencies:
      - webp

    test: |
      system "#{bin}/pixlet --version"
