builds:
  - dir: .goreleaser

    goarch:
      - amd64

    hooks:
      post: ./.goreleaser/fetch-artifacts.sh

checksum:
  name_template: 'checksums.txt'

changelog:
  sort: asc

brews:
  - tap:
      owner: tidbyt
      name: homebrew-tidbyt

    commit_author:
      name: tidbyt-bot
      email: bot@tidbyt.com

    homepage: https://github.com/tidbyt/pixlet

    description: App runtime and UX toolkit for pixel-based apps.

    dependencies:
      - webp

    test: |
      system "#{bin}/pixlet --version"
