// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package fb

import (
	flatbuffers "github.com/google/flatbuffers/go"
)

type AddCircle struct {
	_tab flatbuffers.Table
}

func GetRootAsAddCircle(buf []byte, offset flatbuffers.UOffsetT) *AddCircle {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &AddCircle{}
	x.Init(buf, n+offset)
	return x
}

func FinishAddCircleBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.Finish(offset)
}

func GetSizePrefixedRootAsAddCircle(buf []byte, offset flatbuffers.UOffsetT) *AddCircle {
	n := flatbuffers.GetUOffsetT(buf[offset+flatbuffers.SizeUint32:])
	x := &AddCircle{}
	x.Init(buf, n+offset+flatbuffers.SizeUint32)
	return x
}

func FinishSizePrefixedAddCircleBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.FinishSizePrefixed(offset)
}

func (rcv *AddCircle) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *AddCircle) Table() flatbuffers.Table {
	return rcv._tab
}

func (rcv *AddCircle) X() float64 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		return rcv._tab.GetFloat64(o + rcv._tab.Pos)
	}
	return 0.0
}

func (rcv *AddCircle) MutateX(n float64) bool {
	return rcv._tab.MutateFloat64Slot(4, n)
}

func (rcv *AddCircle) Y() float64 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(6))
	if o != 0 {
		return rcv._tab.GetFloat64(o + rcv._tab.Pos)
	}
	return 0.0
}

func (rcv *AddCircle) MutateY(n float64) bool {
	return rcv._tab.MutateFloat64Slot(6, n)
}

func (rcv *AddCircle) Radius() float64 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(8))
	if o != 0 {
		return rcv._tab.GetFloat64(o + rcv._tab.Pos)
	}
	return 0.0
}

func (rcv *AddCircle) MutateRadius(n float64) bool {
	return rcv._tab.MutateFloat64Slot(8, n)
}

func AddCircleStart(builder *flatbuffers.Builder) {
	builder.StartObject(3)
}
func AddCircleAddX(builder *flatbuffers.Builder, x float64) {
	builder.PrependFloat64Slot(0, x, 0.0)
}
func AddCircleAddY(builder *flatbuffers.Builder, y float64) {
	builder.PrependFloat64Slot(1, y, 0.0)
}
func AddCircleAddRadius(builder *flatbuffers.Builder, radius float64) {
	builder.PrependFloat64Slot(2, radius, 0.0)
}
func AddCircleEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
