// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package fb

import (
	flatbuffers "github.com/google/flatbuffers/go"
)

type AddLineTo struct {
	_tab flatbuffers.Table
}

func GetRootAsAddLineTo(buf []byte, offset flatbuffers.UOffsetT) *AddLineTo {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &AddLineTo{}
	x.Init(buf, n+offset)
	return x
}

func FinishAddLineToBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.Finish(offset)
}

func GetSizePrefixedRootAsAddLineTo(buf []byte, offset flatbuffers.UOffsetT) *AddLineTo {
	n := flatbuffers.GetUOffsetT(buf[offset+flatbuffers.SizeUint32:])
	x := &AddLineTo{}
	x.Init(buf, n+offset+flatbuffers.SizeUint32)
	return x
}

func FinishSizePrefixedAddLineToBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.FinishSizePrefixed(offset)
}

func (rcv *AddLineTo) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *AddLineTo) Table() flatbuffers.Table {
	return rcv._tab
}

func (rcv *AddLineTo) X() float64 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		return rcv._tab.GetFloat64(o + rcv._tab.Pos)
	}
	return 0.0
}

func (rcv *AddLineTo) MutateX(n float64) bool {
	return rcv._tab.MutateFloat64Slot(4, n)
}

func (rcv *AddLineTo) Y() float64 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(6))
	if o != 0 {
		return rcv._tab.GetFloat64(o + rcv._tab.Pos)
	}
	return 0.0
}

func (rcv *AddLineTo) MutateY(n float64) bool {
	return rcv._tab.MutateFloat64Slot(6, n)
}

func AddLineToStart(builder *flatbuffers.Builder) {
	builder.StartObject(2)
}
func AddLineToAddX(builder *flatbuffers.Builder, x float64) {
	builder.PrependFloat64Slot(0, x, 0.0)
}
func AddLineToAddY(builder *flatbuffers.Builder, y float64) {
	builder.PrependFloat64Slot(1, y, 0.0)
}
func AddLineToEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
