// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package fb

import (
	flatbuffers "github.com/google/flatbuffers/go"
)

type AddRectangle struct {
	_tab flatbuffers.Table
}

func GetRootAsAddRectangle(buf []byte, offset flatbuffers.UOffsetT) *AddRectangle {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &AddRectangle{}
	x.Init(buf, n+offset)
	return x
}

func FinishAddRectangleBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.Finish(offset)
}

func GetSizePrefixedRootAsAddRectangle(buf []byte, offset flatbuffers.UOffsetT) *AddRectangle {
	n := flatbuffers.GetUOffsetT(buf[offset+flatbuffers.SizeUint32:])
	x := &AddRectangle{}
	x.Init(buf, n+offset+flatbuffers.SizeUint32)
	return x
}

func FinishSizePrefixedAddRectangleBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.FinishSizePrefixed(offset)
}

func (rcv *AddRectangle) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *AddRectangle) Table() flatbuffers.Table {
	return rcv._tab
}

func (rcv *AddRectangle) X() float64 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		return rcv._tab.GetFloat64(o + rcv._tab.Pos)
	}
	return 0.0
}

func (rcv *AddRectangle) MutateX(n float64) bool {
	return rcv._tab.MutateFloat64Slot(4, n)
}

func (rcv *AddRectangle) Y() float64 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(6))
	if o != 0 {
		return rcv._tab.GetFloat64(o + rcv._tab.Pos)
	}
	return 0.0
}

func (rcv *AddRectangle) MutateY(n float64) bool {
	return rcv._tab.MutateFloat64Slot(6, n)
}

func (rcv *AddRectangle) Width() float64 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(8))
	if o != 0 {
		return rcv._tab.GetFloat64(o + rcv._tab.Pos)
	}
	return 0.0
}

func (rcv *AddRectangle) MutateWidth(n float64) bool {
	return rcv._tab.MutateFloat64Slot(8, n)
}

func (rcv *AddRectangle) Height() float64 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(10))
	if o != 0 {
		return rcv._tab.GetFloat64(o + rcv._tab.Pos)
	}
	return 0.0
}

func (rcv *AddRectangle) MutateHeight(n float64) bool {
	return rcv._tab.MutateFloat64Slot(10, n)
}

func AddRectangleStart(builder *flatbuffers.Builder) {
	builder.StartObject(4)
}
func AddRectangleAddX(builder *flatbuffers.Builder, x float64) {
	builder.PrependFloat64Slot(0, x, 0.0)
}
func AddRectangleAddY(builder *flatbuffers.Builder, y float64) {
	builder.PrependFloat64Slot(1, y, 0.0)
}
func AddRectangleAddWidth(builder *flatbuffers.Builder, width float64) {
	builder.PrependFloat64Slot(2, width, 0.0)
}
func AddRectangleAddHeight(builder *flatbuffers.Builder, height float64) {
	builder.PrependFloat64Slot(3, height, 0.0)
}
func AddRectangleEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
