// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package fb

import "strconv"

type Align int32

const (
	AlignLEFT   Align = 0
	AlignCENTER Align = 1
	AlignRIGHT  Align = 2
)

var EnumNamesAlign = map[Align]string{
	AlignLEFT:   "LEFT",
	AlignCENTER: "CENTER",
	AlignRIGHT:  "RIGHT",
}

var EnumValuesAlign = map[string]Align{
	"LEFT":   AlignLEFT,
	"CENTER": AlignCENTER,
	"RIGHT":  AlignRIGHT,
}

func (v Align) String() string {
	if s, ok := EnumNamesAlign[v]; ok {
		return s
	}
	return "Align(" + strconv.FormatInt(int64(v), 10) + ")"
}
