// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package fb

import (
	flatbuffers "github.com/google/flatbuffers/go"
)

type CanvasOperationList struct {
	_tab flatbuffers.Table
}

func GetRootAsCanvasOperationList(buf []byte, offset flatbuffers.UOffsetT) *CanvasOperationList {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &CanvasOperationList{}
	x.Init(buf, n+offset)
	return x
}

func FinishCanvasOperationListBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.Finish(offset)
}

func GetSizePrefixedRootAsCanvasOperationList(buf []byte, offset flatbuffers.UOffsetT) *CanvasOperationList {
	n := flatbuffers.GetUOffsetT(buf[offset+flatbuffers.SizeUint32:])
	x := &CanvasOperationList{}
	x.Init(buf, n+offset+flatbuffers.SizeUint32)
	return x
}

func FinishSizePrefixedCanvasOperationListBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.FinishSizePrefixed(offset)
}

func (rcv *CanvasOperationList) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *CanvasOperationList) Table() flatbuffers.Table {
	return rcv._tab
}

func (rcv *CanvasOperationList) Operations(obj *CanvasOperation, j int) bool {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		x := rcv._tab.Vector(o)
		x += flatbuffers.UOffsetT(j) * 4
		x = rcv._tab.Indirect(x)
		obj.Init(rcv._tab.Bytes, x)
		return true
	}
	return false
}

func (rcv *CanvasOperationList) OperationsLength() int {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		return rcv._tab.VectorLen(o)
	}
	return 0
}

func CanvasOperationListStart(builder *flatbuffers.Builder) {
	builder.StartObject(1)
}
func CanvasOperationListAddOperations(builder *flatbuffers.Builder, operations flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(0, flatbuffers.UOffsetT(operations), 0)
}
func CanvasOperationListStartOperationsVector(builder *flatbuffers.Builder, numElems int) flatbuffers.UOffsetT {
	return builder.StartVector(4, numElems, 4)
}
func CanvasOperationListEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
