// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package fb

import (
	flatbuffers "github.com/google/flatbuffers/go"
)

type Clear struct {
	_tab flatbuffers.Table
}

func GetRootAsClear(buf []byte, offset flatbuffers.UOffsetT) *Clear {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &Clear{}
	x.Init(buf, n+offset)
	return x
}

func FinishClearBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.Finish(offset)
}

func GetSizePrefixedRootAsClear(buf []byte, offset flatbuffers.UOffsetT) *Clear {
	n := flatbuffers.GetUOffsetT(buf[offset+flatbuffers.SizeUint32:])
	x := &Clear{}
	x.Init(buf, n+offset+flatbuffers.SizeUint32)
	return x
}

func FinishSizePrefixedClearBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.FinishSizePrefixed(offset)
}

func (rcv *Clear) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *Clear) Table() flatbuffers.Table {
	return rcv._tab
}

func ClearStart(builder *flatbuffers.Builder) {
	builder.StartObject(0)
}
func ClearEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
