// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package fb

import (
	flatbuffers "github.com/google/flatbuffers/go"
)

type FillPath struct {
	_tab flatbuffers.Table
}

func GetRootAsFillPath(buf []byte, offset flatbuffers.UOffsetT) *FillPath {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &FillPath{}
	x.Init(buf, n+offset)
	return x
}

func FinishFillPathBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.Finish(offset)
}

func GetSizePrefixedRootAsFillPath(buf []byte, offset flatbuffers.UOffsetT) *FillPath {
	n := flatbuffers.GetUOffsetT(buf[offset+flatbuffers.SizeUint32:])
	x := &FillPath{}
	x.Init(buf, n+offset+flatbuffers.SizeUint32)
	return x
}

func FinishSizePrefixedFillPathBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.FinishSizePrefixed(offset)
}

func (rcv *FillPath) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *FillPath) Table() flatbuffers.Table {
	return rcv._tab
}

func FillPathStart(builder *flatbuffers.Builder) {
	builder.StartObject(0)
}
func FillPathEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
