// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package fb

import (
	flatbuffers "github.com/google/flatbuffers/go"
)

type FontFace struct {
	_tab flatbuffers.Table
}

func GetRootAsFontFace(buf []byte, offset flatbuffers.UOffsetT) *FontFace {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &FontFace{}
	x.Init(buf, n+offset)
	return x
}

func FinishFontFaceBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.Finish(offset)
}

func GetSizePrefixedRootAsFontFace(buf []byte, offset flatbuffers.UOffsetT) *FontFace {
	n := flatbuffers.GetUOffsetT(buf[offset+flatbuffers.SizeUint32:])
	x := &FontFace{}
	x.Init(buf, n+offset+flatbuffers.SizeUint32)
	return x
}

func FinishSizePrefixedFontFaceBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.FinishSizePrefixed(offset)
}

func (rcv *FontFace) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *FontFace) Table() flatbuffers.Table {
	return rcv._tab
}

func (rcv *FontFace) FontName() []byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		return rcv._tab.ByteVector(o + rcv._tab.Pos)
	}
	return nil
}

func FontFaceStart(builder *flatbuffers.Builder) {
	builder.StartObject(1)
}
func FontFaceAddFontName(builder *flatbuffers.Builder, fontName flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(0, flatbuffers.UOffsetT(fontName), 0)
}
func FontFaceEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
