// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package fb

import (
	flatbuffers "github.com/google/flatbuffers/go"
)

type FontHeight struct {
	_tab flatbuffers.Table
}

func GetRootAsFontHeight(buf []byte, offset flatbuffers.UOffsetT) *FontHeight {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &FontHeight{}
	x.Init(buf, n+offset)
	return x
}

func FinishFontHeightBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.Finish(offset)
}

func GetSizePrefixedRootAsFontHeight(buf []byte, offset flatbuffers.UOffsetT) *FontHeight {
	n := flatbuffers.GetUOffsetT(buf[offset+flatbuffers.SizeUint32:])
	x := &FontHeight{}
	x.Init(buf, n+offset+flatbuffers.SizeUint32)
	return x
}

func FinishSizePrefixedFontHeightBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.FinishSizePrefixed(offset)
}

func (rcv *FontHeight) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *FontHeight) Table() flatbuffers.Table {
	return rcv._tab
}

func FontHeightStart(builder *flatbuffers.Builder) {
	builder.StartObject(0)
}
func FontHeightEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
