// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package fb

import (
	flatbuffers "github.com/google/flatbuffers/go"
)

type MeasureString struct {
	_tab flatbuffers.Table
}

func GetRootAsMeasureString(buf []byte, offset flatbuffers.UOffsetT) *MeasureString {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &MeasureString{}
	x.Init(buf, n+offset)
	return x
}

func FinishMeasureStringBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.Finish(offset)
}

func GetSizePrefixedRootAsMeasureString(buf []byte, offset flatbuffers.UOffsetT) *MeasureString {
	n := flatbuffers.GetUOffsetT(buf[offset+flatbuffers.SizeUint32:])
	x := &MeasureString{}
	x.Init(buf, n+offset+flatbuffers.SizeUint32)
	return x
}

func FinishSizePrefixedMeasureStringBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.FinishSizePrefixed(offset)
}

func (rcv *MeasureString) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *MeasureString) Table() flatbuffers.Table {
	return rcv._tab
}

func (rcv *MeasureString) Text() []byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		return rcv._tab.ByteVector(o + rcv._tab.Pos)
	}
	return nil
}

func MeasureStringStart(builder *flatbuffers.Builder) {
	builder.StartObject(1)
}
func MeasureStringAddText(builder *flatbuffers.Builder, text flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(0, flatbuffers.UOffsetT(text), 0)
}
func MeasureStringEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
