// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package fb

import (
	flatbuffers "github.com/google/flatbuffers/go"
)

type Pop struct {
	_tab flatbuffers.Table
}

func GetRootAsPop(buf []byte, offset flatbuffers.UOffsetT) *Pop {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &Pop{}
	x.Init(buf, n+offset)
	return x
}

func FinishPopBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.Finish(offset)
}

func GetSizePrefixedRootAsPop(buf []byte, offset flatbuffers.UOffsetT) *Pop {
	n := flatbuffers.GetUOffsetT(buf[offset+flatbuffers.SizeUint32:])
	x := &Pop{}
	x.Init(buf, n+offset+flatbuffers.SizeUint32)
	return x
}

func FinishSizePrefixedPopBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.FinishSizePrefixed(offset)
}

func (rcv *Pop) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *Pop) Table() flatbuffers.Table {
	return rcv._tab
}

func PopStart(builder *flatbuffers.Builder) {
	builder.StartObject(0)
}
func PopEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
