// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package fb

import (
	flatbuffers "github.com/google/flatbuffers/go"
)

type Push struct {
	_tab flatbuffers.Table
}

func GetRootAsPush(buf []byte, offset flatbuffers.UOffsetT) *Push {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &Push{}
	x.Init(buf, n+offset)
	return x
}

func FinishPushBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.Finish(offset)
}

func GetSizePrefixedRootAsPush(buf []byte, offset flatbuffers.UOffsetT) *Push {
	n := flatbuffers.GetUOffsetT(buf[offset+flatbuffers.SizeUint32:])
	x := &Push{}
	x.Init(buf, n+offset+flatbuffers.SizeUint32)
	return x
}

func FinishSizePrefixedPushBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.FinishSizePrefixed(offset)
}

func (rcv *Push) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *Push) Table() flatbuffers.Table {
	return rcv._tab
}

func PushStart(builder *flatbuffers.Builder) {
	builder.StartObject(0)
}
func PushEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
