// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package fb

import (
	flatbuffers "github.com/google/flatbuffers/go"
)

type Rotate struct {
	_tab flatbuffers.Table
}

func GetRootAsRotate(buf []byte, offset flatbuffers.UOffsetT) *Rotate {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &Rotate{}
	x.Init(buf, n+offset)
	return x
}

func FinishRotateBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.Finish(offset)
}

func GetSizePrefixedRootAsRotate(buf []byte, offset flatbuffers.UOffsetT) *Rotate {
	n := flatbuffers.GetUOffsetT(buf[offset+flatbuffers.SizeUint32:])
	x := &Rotate{}
	x.Init(buf, n+offset+flatbuffers.SizeUint32)
	return x
}

func FinishSizePrefixedRotateBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.FinishSizePrefixed(offset)
}

func (rcv *Rotate) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *Rotate) Table() flatbuffers.Table {
	return rcv._tab
}

func (rcv *Rotate) Angle() float64 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		return rcv._tab.GetFloat64(o + rcv._tab.Pos)
	}
	return 0.0
}

func (rcv *Rotate) MutateAngle(n float64) bool {
	return rcv._tab.MutateFloat64Slot(4, n)
}

func RotateStart(builder *flatbuffers.Builder) {
	builder.StartObject(1)
}
func RotateAddAngle(builder *flatbuffers.Builder, angle float64) {
	builder.PrependFloat64Slot(0, angle, 0.0)
}
func RotateEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
