// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package fb

import (
	flatbuffers "github.com/google/flatbuffers/go"
)

type Scale struct {
	_tab flatbuffers.Table
}

func GetRootAsScale(buf []byte, offset flatbuffers.UOffsetT) *Scale {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &Scale{}
	x.Init(buf, n+offset)
	return x
}

func FinishScaleBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.Finish(offset)
}

func GetSizePrefixedRootAsScale(buf []byte, offset flatbuffers.UOffsetT) *Scale {
	n := flatbuffers.GetUOffsetT(buf[offset+flatbuffers.SizeUint32:])
	x := &Scale{}
	x.Init(buf, n+offset+flatbuffers.SizeUint32)
	return x
}

func FinishSizePrefixedScaleBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.FinishSizePrefixed(offset)
}

func (rcv *Scale) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *Scale) Table() flatbuffers.Table {
	return rcv._tab
}

func (rcv *Scale) X() float64 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		return rcv._tab.GetFloat64(o + rcv._tab.Pos)
	}
	return 0.0
}

func (rcv *Scale) MutateX(n float64) bool {
	return rcv._tab.MutateFloat64Slot(4, n)
}

func (rcv *Scale) Y() float64 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(6))
	if o != 0 {
		return rcv._tab.GetFloat64(o + rcv._tab.Pos)
	}
	return 0.0
}

func (rcv *Scale) MutateY(n float64) bool {
	return rcv._tab.MutateFloat64Slot(6, n)
}

func ScaleStart(builder *flatbuffers.Builder) {
	builder.StartObject(2)
}
func ScaleAddX(builder *flatbuffers.Builder, x float64) {
	builder.PrependFloat64Slot(0, x, 0.0)
}
func ScaleAddY(builder *flatbuffers.Builder, y float64) {
	builder.PrependFloat64Slot(1, y, 0.0)
}
func ScaleEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
