// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package fb

import (
	flatbuffers "github.com/google/flatbuffers/go"
)

type SetFontFace struct {
	_tab flatbuffers.Table
}

func GetRootAsSetFontFace(buf []byte, offset flatbuffers.UOffsetT) *SetFontFace {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &SetFontFace{}
	x.Init(buf, n+offset)
	return x
}

func FinishSetFontFaceBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.Finish(offset)
}

func GetSizePrefixedRootAsSetFontFace(buf []byte, offset flatbuffers.UOffsetT) *SetFontFace {
	n := flatbuffers.GetUOffsetT(buf[offset+flatbuffers.SizeUint32:])
	x := &SetFontFace{}
	x.Init(buf, n+offset+flatbuffers.SizeUint32)
	return x
}

func FinishSizePrefixedSetFontFaceBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.FinishSizePrefixed(offset)
}

func (rcv *SetFontFace) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *SetFontFace) Table() flatbuffers.Table {
	return rcv._tab
}

func (rcv *SetFontFace) FontFace(obj *FontFace) *FontFace {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		x := rcv._tab.Indirect(o + rcv._tab.Pos)
		if obj == nil {
			obj = new(FontFace)
		}
		obj.Init(rcv._tab.Bytes, x)
		return obj
	}
	return nil
}

func SetFontFaceStart(builder *flatbuffers.Builder) {
	builder.StartObject(1)
}
func SetFontFaceAddFontFace(builder *flatbuffers.Builder, fontFace flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(0, flatbuffers.UOffsetT(fontFace), 0)
}
func SetFontFaceEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
