// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package fb

import (
	flatbuffers "github.com/google/flatbuffers/go"
)

type Translate struct {
	_tab flatbuffers.Table
}

func GetRootAsTranslate(buf []byte, offset flatbuffers.UOffsetT) *Translate {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &Translate{}
	x.Init(buf, n+offset)
	return x
}

func FinishTranslateBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.Finish(offset)
}

func GetSizePrefixedRootAsTranslate(buf []byte, offset flatbuffers.UOffsetT) *Translate {
	n := flatbuffers.GetUOffsetT(buf[offset+flatbuffers.SizeUint32:])
	x := &Translate{}
	x.Init(buf, n+offset+flatbuffers.SizeUint32)
	return x
}

func FinishSizePrefixedTranslateBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.FinishSizePrefixed(offset)
}

func (rcv *Translate) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *Translate) Table() flatbuffers.Table {
	return rcv._tab
}

func (rcv *Translate) Dx() float64 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		return rcv._tab.GetFloat64(o + rcv._tab.Pos)
	}
	return 0.0
}

func (rcv *Translate) MutateDx(n float64) bool {
	return rcv._tab.MutateFloat64Slot(4, n)
}

func (rcv *Translate) Dy() float64 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(6))
	if o != 0 {
		return rcv._tab.GetFloat64(o + rcv._tab.Pos)
	}
	return 0.0
}

func (rcv *Translate) MutateDy(n float64) bool {
	return rcv._tab.MutateFloat64Slot(6, n)
}

func TranslateStart(builder *flatbuffers.Builder) {
	builder.StartObject(2)
}
func TranslateAddDx(builder *flatbuffers.Builder, dx float64) {
	builder.PrependFloat64Slot(0, dx, 0.0)
}
func TranslateAddDy(builder *flatbuffers.Builder, dy float64) {
	builder.PrependFloat64Slot(1, dy, 0.0)
}
func TranslateEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
